import Header from './components/Header'
import './globals.css'
import type { Metadata } from 'next'
import Providers from './Providers'



export const metadata: Metadata = {
  title: 'IMDB Clone',
  description: 'Generated by create Oguzhan Sandi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/*Header*/}
          <Header/>
          {/*Navbar*/}
          {/*SearchBox*/}


          {children}
        </Providers>
      </body>
    </html> 
  )
}
